---

- name: configure raspberry pi's
  hosts: raspberries
  gather_facts: true
  become: yes
  vars:
    containerd_version: 1.7.2
    containerd_cni_plugin_version: 1.3.0
    crictl_version: 1.26.1
    kubeadm_version: 1.27.3-00
    kubelet_version: 1.27.3-00
    kubectl_version: 1.27.3-00
  roles:
    - update_and_install
    - install_containerd
    - install_kubernetes
