---



- name: turn on preserve_hostname
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname: false'
    line: 'preserve_hostname: true'

- name: set current node hostname
  command: hostnamectl set-hostname {{ new_hostname }}
  when: new_hostname != ansible_hostname

- name: update the cache if older than 6 hours
  apt:
    cache_valid_time: 21600

- name: upgrade
  apt:
    upgrade: "True"

- name: ensure packages installed
  apt:
   pkg:
   - vim
   - etcd-client  # todo controller only
   state: present

- name: perform autoclean
  apt:
    autoclean: yes
    force_apt_get: yes

- name: perform autoremove
  apt:
    autoremove: yes
    force_apt_get: yes
