---

# TODO break up long urls
# TODO hold versions
# - name: Hold containerd.io upgrades
#   dpkg_selections:
#     name: containerd.io
#     selection: hold

- name: download containerd with checksum
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-arm64.tar.gz
    dest: /tmp/containerd-{{ containerd_version }}-linux-arm64.tar.gz
    checksum: sha256:https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-arm64.tar.gz.sha256sum
    mode: '0755'

- name: extract containerd to /usr/local
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/containerd-{{ containerd_version }}-linux-arm64.tar.gz
    dest: /usr/local

- name: create systemd service directory if it does not exist
  file:
    path: /usr/local/lib/systemd/system
    state: directory
    mode: '0755'

- name: download containerd.service unit file
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /usr/local/lib/systemd/system/containerd.service
    mode: '0755'

- name: enable and start containerd
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: containerd

- name: update the cache if older than 6 hours
  apt:
    cache_valid_time: 21600

- name: ensure runc is installed
  apt:
    name: runc

- name: download cni plugin with checksum
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v{{containerd_cni_plugin_version}}/cni-plugins-linux-arm64-v{{containerd_cni_plugin_version}}.tgz
    dest: /tmp/cni-plugins-linux-arm64-v{{containerd_cni_plugin_version}}.tgz
    checksum: sha1:https://github.com/containernetworking/plugins/releases/download/v{{containerd_cni_plugin_version}}/cni-plugins-linux-arm64-v{{containerd_cni_plugin_version}}.tgz.sha1
    mode: '0755'

- name: create cni bin directory if it does not exist
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: extract cni plugin to /opt/cni/bin
  unarchive:
    remote_src: true
    src: /tmp/cni-plugins-linux-arm64-v1.3.0.tgz
    dest: /opt/cni/bin

# referencing the url for the checksum inside get_url has issues
- name: download checksum for crictl
  uri:
    url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-arm64.tar.gz.sha256"
    return_content: true
  register: sha256_crictl

- name: get checksum from response
  set_fact:
    crictl_checksum: "{{ sha256_crictl.content.split('  ')[0] }}"

- name: download crictl cli tool for use with containerd
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-arm64.tar.gz
    dest: /tmp/crictl-v{{ crictl_version }}-linux-arm64.tar.gz
    checksum: sha256:{{ crictl_checksum }}
    mode: '0755'

- name: extract crictl to /usr/local/bin
  unarchive:
    remote_src: true
    src: /tmp/crictl-v{{ crictl_version }}-linux-arm64.tar.gz
    dest: /usr/local/bin

- name: create containerd config directory if it does not exist
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: generate default containerd config file every time
  shell: containerd config default > /etc/containerd/config.toml
  changed_when: False

- name: make crictl config file
  copy:
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 2
      debug: true
      pull-image-on-create: false
    dest: /etc/crictl.yaml
